default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['DATABASE_USER'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  reconnect: true

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_test

production:
  <<: *default

staging:
  <<: *default
